FROM node:16.14

WORKDIR /client
ENV PATH /client/node_modules/.bin:$PATH
ENV CHOKIDAR_USEPOLLING=TRUE

# install package
COPY ["package*.json", "./"]
RUN ["npm", "install", "--silent"]

# run npm server
COPY [".", "."]

CMD ["node", "node_modules/react-scripts/scripts/start.js"]