# This is for develop server
version: "3"

services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    stdin_open: true
    build: nginx
    volumes:
      - ./nginx/nginx.dev-server:/etc/nginx/conf.d
      - ./client/build:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - app-tier
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api_blue:
    container_name: api_blue
    build:
      context: ./server
      dockerfile: Dockerfile.dev-server
    env_file: ./server/.env
    networks:
      - app-tier
    restart: always

  api_green:
    container_name: api_green
    build:
      context: ./server
      dockerfile: Dockerfile.dev-server
    env_file: ./server/.env
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
