version: "3"

services:
  frontend:
    container_name: frontend
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file: ./client/.env
    volumes:
      - /client/node_modules
      - ./client/:/client
    networks:
      - app-tier
    tty: true
    restart: always
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:8080
    volumes:
      - ./client/src/css:/src/css
      - ./nginx/nginx.FEBE.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-tier
    restart: always
    command: "nginx -g 'daemon off;'"

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - 5000:5000
    volumes:
      - /server/node_modules
      - ./server/:/server
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
