version: "3"

services:
  frontend:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - /client/node_modules
      - ./client/:/client
    ports:
      - 3000:3000
    networks:
      - app-tier
    tty: true

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - /server/node_modules
      - ./server/:/server
    networks:
      - app-tier
    restart: always

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
