# for local backend development

version: "3"

services:
  nginx:
    container_name: nginx
    build: ./nginx-dev
    ports:
      - 8080:8080
    volumes:
      - ./nginx-dev/nginx-BE.conf:/etc/nginx/conf.d/nginx.conf
      - ./scripts/dev/reload-nginx.sh:/scripts/relaod-nginx.sh
    networks:
      - app-tier
    restart: always
    command: ["/scripts/relaod-nginx.sh"]

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - 5000:5000
    volumes:
      - /server/node_modules
      - ./server/:/server
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
