version: "3"

services:
  frontend:
    container_name: frontend
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file: ./client/.env
    volumes:
      - /client/node_modules
      - ./client/:/client
    ports:
      - ${LOCALHOST_PORT:-3000}:3000
    networks:
      - app-tier
    tty: true
    restart: always
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx-dev
    ports:
      - 80:80
    volumes:
      - ./client/src/css:/src/css
    depends_on:
      - frontend
    networks:
      - app-tier
    restart: always

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - 5000:5000
    volumes:
      - /server/node_modules
      - ./server/:/server
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
