# This is for develop server
version: "3"

services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    stdin_open: true
    build: nginx
    volumes:
      - ./nginx/nginx.dev-server:/etc/nginx/conf.d
      - ./client/src/css:/static-files/css
      - ./client/build:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - app-tier
    depends_on:
      - api
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.dev-server
    env_file: ./server/.env
    volumes:
      - /server/node_modules
      - ./server/:/server
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
