FROM node:16.16

#이미지 안에 애플리케이션 코드를 넣기위한 디렉터리 생성
WORKDIR /server
ENV PATH /server/node_modules/.bin:$PATH

#앱 의존성 설치
#가능한 경우(npm@5+) package.json과 package-lock.json을 모두 복사하기 위해 와일드카드를 사용
COPY ["package*.json", "./"]

# swagger 사용하기 위해 production mode가 아닌 develop mode로 install
RUN ["npm", "install"]

# 앱 소스 추가
COPY [".", "."]

# 서버 시작
CMD ["node", "main.js"]
