/**
 * 검색 결과로 관련된 계산기 더미
 */
export const CALCULET = [
  {
    id: 1,
    title: "사칙연산 계산기",
    description: "사칙연산을 하는 계산기입니다.",
    category_main: "수학",
    category_sub: "계산",
    user_name: "bsa0322",
    view_cnt: 20,
    like_cnt: 1,
    bookmark_cnt: 1,
  },
  {
    id: 5,
    title: "사칙 계산기",
    description: "사칙 하는 계산기입니다.",
    category_main: "수학",
    category_sub: "계산",
    user_name: "bsa3333",
    view_cnt: 200,
    like_cnt: 12,
    bookmark_cnt: 11,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
  {
    id: 100,
    title: "계산기",
    description: "계산기입니다.",
    category_main: "과학-공학",
    category_sub: "계산",
    user_name: "b33333333",
    view_cnt: 2000,
    like_cnt: 102,
    bookmark_cnt: 101,
  },
];
