name: (DEV) reload nginx

on:
  push:
    branches:
      - develop
    paths:
      - nginx/nginx.dev-server/*

jobs:
  reload-nginx:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: reload nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_IP_ADDRESS }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          script: "cd /home/ubuntu/project/application; git pull origin develop; docker exec frontend nginx -s reload;"
