name: (DEV) deploy backend

on:
  push:
    branches:
      - develop
    paths:
      - 'server/**'
jobs:
  deploy-backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_IP_ADDRESS }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          script: "cd /home/ubuntu/project/application; ./scripts/dev-server/rebuild-backend.sh"
